global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 10
  static_map: true
  # rolling_window: true

  plugins:
    - {name: height_layer,            type: "costmap_2d::StaticLayer"}

height_layer:
    enabled:                true
    map_topic:              map
    first_map_only:         false
    unknown_cost_value:     -1
    lethal_cost_threshold:  100
    subscribe_to_updates:   false
    track_unknown_space:    true
    use_maximum:            false     
    trinary_costmap:        false       



