plugins: 
  - {name: social_layer,          type: "social_navigation_layers::ProxemicLayer"}
  - {name: social_passing_layer,  type: "social_navigation_layers::PassingLayer"}
  - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 20.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  inf_is_valid: false

  obstacle_layer:
    laser_scan_right_sensor: {sensor_frame: /base_link, data_type: LaserScan,
            topic: scan_right, marking: true, clearing: true,
            observation_persistence: 0.0,
            raytrace_range: 11.0, obstacle_range: 5.6,
            expected_update_rate: 0.1}

    laser_scan_left_sensor: {sensor_frame: /base_link, data_type: LaserScan,
                                topic: scan_left, marking: true, clearing: true,
                                observation_persistence: 0.0,
                                raytrace_range: 11.0, obstacle_range: 5.6,
                                expected_update_rate: 0.1}
