tracker_width_fov: 1.23220245191      # 70.6*M_PI/180
tracker_height_fov: 1.0471975512      # 60.0*M_PI/180
tracker_cam_width: 512
tracker_cam_height: 424
seg_threshold: 300                    # in mm