slowing_radius: 1.5
deception_target_change_distance: 0.3

# EASY PARAMS
# max_force: 5.5 # maximum force the motor can apply to the vehicle
# max_speed: 0.5 # maximum speed of the vehicle

# MEDIUM PARAMS
min_mass: 6.0  # minimum mass of the vehicle
base_mass: 8.0 # starting mass of the vehicle
max_mass: 10.0 # maximum mass of the vehicle

min_force: 4.0
base_force: 5.0
max_force: 6.0  # maximum force the motor can apply to the vehicle

min_speed: 0.6  # minum speed of vehicle
# base_speed: 0.85 # starting speed of vehicle
base_speed: 0.7
max_speed: 1.0  # maximum speed of the vehicle

# DIFFICULT PARAMS
# max_force: 5.5 # maximum force the motor can apply to the vehicle
# max_speed: 1.0 # maximum speed of the vehicle

# TOPICS FOR TURTLESIM
# vel_topic_sub: "/turtle1/vel"
# vel_topic_pub: "/turtle1/cmd_vel"
# pose_topic: "/turtle1/my_pose"

# TOPICS FOR TRISKAR
vel_topic_sub: "/vel"
vel_topic_pub: "/game_navigation/unsafe/cmd_vel"