to_pose_array:
    detectors:                                         # Add detectors under this namespace
        upper_body_detector:                           # Name of detector (used internally to identify them. Has to be unique.
            topic: "/robogame/player_global_position"  # The topic on which the geometry_msgs/PoseArray is published
            point_name: "position"                     # The name of the point containing the coordinates in question
        leg_detector:
            topic: "/people_tracked"
            point_name: "position"
