format: [
            "pipe_id", 
            "isTowerEnable", 
            "isCaptured", 
            "isTowerDown", 
            "distanceLeft",
            "distanceCenter",
            "distanceRight",
            "led1",
            "led2",
            "led3",
            "led3" 
                        ]