######################################
# Location for data logging
######################################
trueskill_database_path: "/home/airlab/catkin_ws/src/Robotower2.0/parameter_adaptation/data/trueskill"
microgame_db_path: "/home/airlab/catkin_ws/src/Robotower2.0/parameter_adaptation/data/microgame.db"

######################################
# Topics for relevant ROS messages
######################################
microgame_outcome_topic: "/microgame_outcome"
parameter_set_topic: "/parameter_id"
reset_topic: "/game_manager/reset"
change_player_topic: "/change_player"

######################################
# Name and surname for current player
######################################
player_name: "Video"
player_surname: "Tesi"