tracker_width_fov: 1.23220245191      # 70.6*M_PI/180
tracker_height_fov: 1.0471975512      # 60.0*M_PI/180
tracker_cam_width: 512
tracker_cam_height: 424
camera_namespace: "/kinect2"
queue_size: 5
show_frame: false
color_frame: "/sd/image_color_rect"
depth_frame: "/sd/image_depth_rect"
seg_threshold: 300                    # in mm
h_min: 127
s_min: 99
v_min: 39
h_max: 165
s_max: 256
v_max: 256