local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  inf_is_valid: true
  obstacle_layer:
    laser_scan_sensor: {sensor_frame: /base_link, data_type: LaserScan,
                     topic: scan, marking: true, clearing: true,
                     observation_persistence: 0.0,
                     raytrace_range: 11.0, obstacle_range: 5.6,
                     expected_update_rate: 0.4}
